### ISSUE TITLE
Publishing trained fairseq model on pytorch hub 

### ISSUE THREAD

**Issue by Skylixia** [pytorch/hub#122]
Hello, 

I trained my Roberta model following this tutorial, now I have the checkpoint directory with all checkpoints.pt (including best_checkpoint.pt) how to make use of these to publish on pytorch hub ?
In the [documentation](https://pytorch.org/docs/stable/hub.html), it's indicated to create a hubconf.py with an entrypoint. However, I don't see how to make this entrypoint with the checkpoints files I get from training Roberta with fairseq. 
Any suggestions ?

**Comment by ailzhang** [comment]
You entrypoint takes `pretrained` argument which should load checkpoint to model when it's set to True. See an example here: https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py#L62
Closing as resolved, please feel free to reopen if you have followup questions. Thanks!
