### ISSUE TITLE
github HTTP Error 404 (nvidia Tacotron2)

### ISSUE THREAD

**Issue by hackIS** [pytorch/hub#162]
Tacotron2: https://pytorch.org/hub/nvidia_deeplearningexamples_tacotron2/ 

I get for the
https://api.ngc.nvidia.com/v2/models/nvidia/tacotron2pyt_fp32/versions/1/files/nvidia_tacotron2pyt_fp32_20190306.pth

an HTTP Error 404 message.

I run this script in Colab with GPU since several weeks regularly. today I get an error message.... I deleted the cache already
<img width="832" alt="tacotron_error" src="https://user-images.githubusercontent.com/73347438/97008120-b7c38100-1542-11eb-9e4a-b071f1f8c2d1.png">

**Comment by ArturoRR97** [comment]
I got the same error with the SSD model [](url)

**Comment by sowgali** [comment]
Same issue here. I think Nvidia's SSD model has been updated on their website, but not in the hub. So it is pointing to the old link and hence the error. You can visit this [Link](https://ngc.nvidia.com/catalog/resources/nvidia:ssd_for_pytorch/setup) for more information.

**Comment by hackIS** [comment]
and how to change that link to the new link in the hub? who is doing that?

**Comment by ailzhang** [comment]
Oh this issue should go to https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2 instead since the link should be updated there.

**Comment by BalajiB197** [comment]
even I am facing the same issue, my development is stopped due to the dependency, please let me know how we can plan for a workaround to this issue.

**Comment by soumith** [comment]
@GrzegorzKarchNV @nvpstr @nv-kkudrynski can we please get this fixed in your repo asap. The checkpoint URLs have changed, and I believe you might have forgot to update the URLs in your hubconf.py

**Comment by nv-kkudrynski** [comment]
Working on this now. Thanks for the notice.

**Comment by nv-kkudrynski** [comment]
I fixed this and tested via torch.hub googlecolab. It is back to operational. Sorry for inconveniece.
Thx for letting us know @soumith. After the weekend I plan to update hubconf (and possibly the torch.hub md files) to benefit from our new checkpoints.

**Comment by soumith** [comment]
thank you for the quick fix!
