### ISSUE TITLE
Huge Amounts for Traffic For Torch Hub Published Models

### ISSUE THREAD

**Issue by snakers4** [pytorch/hub#187]
Hi guys,

Since `torch.hub` is so great I would just want to ask some friendly advice on this topic
- https://github.com/snakers4/silero-models/issues/49

Maybe someone here faced similar issues or knows what it is.
Or maybe there are some CI jobs gone rogue.

**Comment by snakers4** [comment]
What it also relevant, once I migrated to new URL and updated the `yml` [file](https://github.com/snakers4/silero-models/blob/master/models.yml) it took some time (several hours) for this to start on our own hosting (compared to S3 bucket)

**Comment by ailzhang** [comment]
@snakers4 thanks a lot for reporting! We don't have visibility on where these ips come from, but it might be possible people setup CI/experiments from your model. (but really if it's experiments they should hit their local cache :P 


But we do understand hosting can be some burden for model owners with limited budget. One way we think of to help relieve the burden is if less than 2GB, it’s recommended to attach it to a project release and use the url from the release, e.g. https://github.com/ailzhang/torchhub_example/releases. 
Let us know if this helps. 

cc: @soumith @jspisak to see if there's anything else we can do to help.

**Comment by snakers4** [comment]
Yeah, we thought about creatively using GitHub releases, but even now (before the multiple new planned releases) we already have more than 2GB of models `2.4G silero_models`, though ofc we can publish models iteratively. I am not entirely sure that GitHub releases is really intended for such use, but this is a viable option nevertheless (but we will be just shifting the hot potato instead of solving the underlying issue).

To be honest, I am not actually worried about incurring fees (there are stellar hosting options like Hetzner), but just about finding out what is causing the traffic. Looks like the country ban works, though it is a poor solution long-term:

![image](https://user-images.githubusercontent.com/12515440/108946944-884b8f00-7670-11eb-9867-b33f52d49e37.png)
![image](https://user-images.githubusercontent.com/12515440/108947053-c779e000-7670-11eb-8160-a11a32e7f883.png)
![image](https://user-images.githubusercontent.com/12515440/108947098-da8cb000-7670-11eb-857b-ec51b0ec9559.png)

All of these are AWS, Ireland, `torch.hub` useragent (whatever it means),  `/models/en/en_v2_jit.model` model
Maybe it is just some CI job for building the torch.hub website, maybe just worth investigating

**Comment by snakers4** [comment]
> I am not entirely sure that GitHub releases is really intended for such use

Also also though GitHub provides a sane estimation of the repo popularity with its stars / traffic tab, just counting model hits is probably a better metric, idk

**Comment by jspisak** [comment]
+1 to hosting on GitHub if you can fall below the limit. We ourselves don't host hub models to avoid incurring the liabilities that are involved.

**Comment by snakers4** [comment]
We checked the hosting logs again
99% of traffic was this "CI job" (?) from Ireland
Colab and various servers across the world continue to work properly
Hm, interesting

**Comment by ailzhang** [comment]
@snakers4 Yea in this case it's likely better to ban the ip range and people might come back and reach out if it's a valid use case :D

**Comment by snakers4** [comment]
Well in any case if "the job" is not yours
Then let's close 
Stat tuned for new models)
