### ISSUE TITLE
DeeplabV3-Resnet101. Where is the mIOU calculation and postprocessing code?

### ISSUE THREAD

**Issue by ashg1910** [pytorch/hub#218]
The following link mentions mIOU = 67.4
https://pytorch.org/hub/pytorch_vision_deeplabv3_resnet101/

Is there any codebase where we can refer the evaluation and postprocessing code?

**Comment by NicolasHug** [comment]
@ashg1910 this model originally comes from torchvision. You should be able to find all the relevant info regarding training / evaluation in the `reference` part of torchvision: https://github.com/pytorch/vision/tree/master/references/segmentation
