### ISSUE TITLE
CI test is broken. New pull request cannot be merged.

### ISSUE THREAD

**Issue by PeterL1n** [pytorch/hub#224]
I have created a new pull request to add a new model to Hub: https://github.com/pytorch/hub/pull/223, but the CI test is broken. Can this be fixed so new models can be merged?

**Comment by NicolasHug** [comment]
Thanks for the report @PeterL1n , yes the CI has unfortunately been down for too long now. We're working on getting it back to normal. I'll close this PR as the main issue is tracked in https://github.com/pytorch/hub/issues/212 and in the related PRs / issues.

Regarding your PR (which I'll try to review soon), you should be able to get the CI running by first applying this temporary workaround: https://github.com/pytorch/pytorch/issues/61755#issuecomment-885801511
