### ISSUE TITLE
libtorch_hip.so: cannot open shared object file: No such file or directory silero model  error on heroku

### ISSUE THREAD

**Issue by sekpona1-crypto** [pytorch/hub#262]
Thank you for this amazing model. I run it on my  computer and it work sucessufully with torch=1..10.1 and torchaudio1.10.1. But if i push it ro heroku, it not work. 
Because of heroku slug size rules, in requirements i put torch==1.10.1+cpu torch==1.10.1 . 

I have thise error: libtorch_hip.so: cannot open shared object file: No such file or directory. 

Please, help me.

**Comment by NicolasHug** [comment]
Hi @sekpona1-crypto , it looks like the issue you're having is related to one of the (various) silero models that are exposed via torchhub, but it doesn't seem directly related to torchhub. Torchhub is just a way of downloading and running these models. As a result I believe your issue could be better answered in the silero repo https://github.com/snakers4/silero-models. If you submit an issue over there, I would encourage you to provide as much details as possible, in particular the full error traceback, and the exact code that  you tried to execute. This would help people help you.

I'll close this one, hope you don't mind.
