### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by SubhransuSekharBhattacharjee-01** [pytorch/hub#264]

**Comment by NicolasHug** [comment]
Hi @SubhransuSekharBhattacharjee-01 , would you mind providing some details on the error you're getting? What code did you try to execute, what is the full error message, what versions of pytorch are you using, etc. ?

I'll close this issue but if your problem persists please feel free to open a new one with the required details above. Thanks!

**Comment by SubhransuSekharBhattacharjee-01** [comment]
Hi Nicholas, no issues, it has been solved.
