### ISSUE TITLE
Silero models are failing

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/hub#267]
The silero models are failing according to a recent CI run: https://app.circleci.com/pipelines/github/pytorch/hub/1563/workflows/f1cf4147-4fd6-48ec-8af8-5f3ce283ec56/jobs/1999

The issue seems to be internal to the silero repo and related to torchaudio:

```py
E           Traceback (most recent call last):
E             File "python_code/snakers4_silero-vad_language.py", line 13, in <module>
E               wav = read_audio(f'{files_dir}/de.wav')
E             File "/home/circleci/.cache/torch/hub/snakers4_silero-vad_master/utils_vad.py", line 80, in read_audio
E               wav, sr = torchaudio.load(path)
E             File "/home/circleci/miniconda3/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 153, in load
E               return torch.ops.torchaudio.sox_io_load_audio_file(
E           RuntimeError: Error loading audio file: failed to open file /home/circleci/.cache/torch/hub/snakers4_silero-vad_master/files/de.wav

```

@snakers4 I believe you authored the models in https://github.com/pytorch/hub/pull/182, would you mind taking a look? :)
Thanks!

**Comment by snakers4** [comment]
@adamnsandle this is related to a fix, where we removed files from the repo
can you please fix this in torch hub?

**Comment by NicolasHug** [comment]
Closed by https://github.com/pytorch/hub/pull/268

Thanks a lot @adamnsandle  and @snakers4
