### ISSUE TITLE
RuntimeError: invalid hash value

### ISSUE THREAD

**Issue by mateuszbuda** [pytorch/hub#29]
I keep getting an error when loading state dict form url:

```
Downloading: "https://github.com/mateuszbuda/brain-segmentation-pytorch/archive/master.zip" to /root/.cache/torch/hub/master.zip
Downloading: "https://github.com/mateuszbuda/brain-segmentation-pytorch/blob/master/weights/unet-e012d006.pt" to /root/.cache/torch/checkpoints/unet-e012d006.pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 340, in load
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/mateuszbuda_brain-segmentation-pytorch_master/hubconf.py", line 25, in unet
    checkpoint, progress=False, map_location=device
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 433, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 377, in _download_url_to_file
    .format(hash_prefix, digest))
RuntimeError: invalid hash value (expected "e012d006", got "7f29ab803d816cd5e7036edba138876058fe5b3ce89ad58f48eca48d05013c1e")
```

And every time I try, I get a different hash value

```
RuntimeError: invalid hash value (expected "e012d006", got "72a1672284d86564ba1d7bc42b0adfdc79d20fee5b474e920afb67618fc2db35")
```

```
RuntimeError: invalid hash value (expected "e012d006", got "6aac34dc3952bc3f033e0d6051f6058c15e5f2877773c852c32063d9213e37a8")
```

What is the recommended way to load weights that are stored on github?
I followed this guide: https://pytorch.org/docs/stable/hub.html#publishing-models

**Comment by ailzhang** [comment]
@mateuszbuda I think what's happening here is we require the name to be suffixed with "first 8 digits of SHA256" of the content. Try renaming it to `unet-7f29ab80.pt`
https://pytorch.org/docs/master/model_zoo.html#torch.utils.model_zoo.load_url
Please let me know if that fixes it for you. 
I will update the hub documentation. :)

**Comment by ailzhang** [comment]
Btw if your weights in in the same github repo, you can use `load_state_dict` directly without `torch.hub.load_state_dict_from_url`

**Comment by mateuszbuda** [comment]
Thank you for the suggestions @ailzhang.
It didn't help to rename it to `unet-7f29ab80.pt` since every time I load it, I'm getting a different hash value.
I tried using `load_state_dict` but couldn't figure out `path_to_saved_checkpoint` format.
Should it include github username and/or repo name?
Assuming that I store the weights file in `weights/unet.pt`, how should I use load state dict:

```
state_dict = torch.load("weights/unet.pt")
model.load_state_dict(state_dict)
```

or

```
state_dict = torch.load("/mateuszbuda/brain-segmentation-pytorch/weights/unet.pt")
model.load_state_dict(state_dict)
```

or in a different way?

**Comment by ailzhang** [comment]
Yea in your case load_from_url API won't fit. I believe 
```
state_dict = torch.load("weights/unet.pt")
model.load_state_dict(state_dict)
```
should work. You can push the change to a branch and test it using `torch.load('xxx/xxx:branch', 'model')`

**Comment by mateuszbuda** [comment]
It worked! Thank you.

**Comment by mateuszbuda** [comment]
@ailzhang Unfortunately, using `weights/unet.pt` as `path_to_saved_checkpoint` works only if I run `torch.load` from a local folder where I cloned the repo and `weights/unet.pt` exists.
If I run it from a different location, e.g. a home folder, it fails:

```
FileNotFoundError: [Errno 2] No such file or directory: 'weights/unet.pt'
```

Details here: https://circleci.com/gh/pytorch/hub/131?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I also tried it from a different folder on a local computer with the same result.

I thought about constructing the path dynamically as it is done in [torch.hub.py](https://github.com/pytorch/pytorch/blob/master/torch/hub.py):

```
os.path.join(torch.hub.hub_dir, "_".join([repo_owner, repo_name, branch]), "weights/unet.pt")
```

Do you know how it should be done?
Is there any example of loading weights from a file hosted on github?
Also, do you know why downloading a file form guthub url generates different sha256 every time it's downloaded?

Thanks for help.

**Comment by rwightman** [comment]
@mateuszbuda  In general, aside from the issues you're having, I wouldn't say checking binary weights in to the git/github repos is the best approach for a number of reasons...

One thing that works quite well though, is adding the weights as assets in a release tag and using the resulting URL with the standard url based loading methods. It's free, fast, versionable (using new release tags), and gives you a direct link, only downside is a rather long URI.

E.g.: https://github.com/rwightman/pytorch-image-models/releases

**Comment by ailzhang** [comment]
@mateuszbuda  I will take a look on the local weights later today, in the mean while, would you mind taking a look at @rwightman 's solution? Thanks!

**Comment by mateuszbuda** [comment]
@rwightman Thank you, I followed your suggestion and it worked.
@ailzhang If loading weights from a file on github repo is an option, it would be good to have an example for it.

**Comment by ailzhang** [comment]
@mateuszbuda I got local weights to work in https://github.com/ailzhang/brain-segmentation-pytorch/commit/e17d358a520d374ad58810a2c7aa5537a9500305 in case you are interested in using it. 
I will update the documentation with an example. Thanks!

**Comment by mateuszbuda** [comment]
Thanks for figuring this out.
Anyway, I'll stick to the method suggested by @rwightman.
I think it should be recommended.
