### ISSUE TITLE
Extension of Torch Hub

### ISSUE THREAD

**Issue by 17sid** [pytorch/hub#320]
I recently visited the models section of Hugging Face and I liked it's ease of use and how everybody's model's were showcased. It had many features like Live hosted demo, documentation, community reviews and everything that we might need to use their model effectively. So I was thinking if these features are present in Torch Hub because I can't find them. If they are present can any one give me it's link else can we emulate the feature mentioned above or create a central repository of models which would have similar features.

**Comment by soumith** [comment]
these features aren't present in torch hub, and at this point we aren't proactively looking to grow it as the folks maintaining it don't have the bandwidth or priority.
the `torch.hub` API as written is convenient and is good to maintain though.

If anyone wants to proactively grow and add features to torch hub, I think we'd be happy to review and merge (and maybe eventually add them as a maintainer)
