### ISSUE TITLE
Proposal for consistency in wording `ImageNet`

### ISSUE THREAD

**Issue by cpprhtn** [pytorch/hub#336]
The ImageNet dataset has a variety of notations.

`imagenet` `Imagenet` `ImageNet` `IMAGENET`

Why not call it `ImageNet`?

If you agree with the proposal, I plan to revise it.

Thanks :)

**Comment by NicolasHug** [comment]
Hi @cpprhtn , thanks for the proposal. It sounds like a reasonable thing to do, feel free to submit a PR.

**Comment by cpprhtn** [comment]
@NicolasHug Thanks!
I have completed the modification except for the ImageNet words included in some url

**Comment by NicolasHug** [comment]
Closed by https://github.com/pytorch/hub/pull/338, thanks for the proposal and the PR @cpprhtn !
