### ISSUE TITLE
using static dowloaded .pt small model for predictionas , encountering this isssue :  prediction = midas(input_batch) TypeError: 'collections.OrderedDict' object is not callable 

### ISSUE THREAD

**Issue by harry9425** [pytorch/hub#337]

**Comment by NicolasHug** [comment]
Hi @harry9425 , sorry but we can't really help without a reproducible code example. Please show what lines of code you ran, and paste the error traceback.

To be honest, looking at the error message, I suspect that the issue doesn't come from torchhub but rather from the [way you use] the midas model; in which case this isn't an error to report here, but rather on the original model's repo.
