### ISSUE TITLE
Links broken on Pytorch-Transformers page

### ISSUE THREAD

**Issue by afifaniks** [pytorch/hub#339]
Reference links for DistilBERT are broken in [PyTorch-Transformers](https://pytorch.org/hub/huggingface_pytorch-transformers/) page. Both of the URLs for DistilBERT are now unreachable. 
![image](https://github.com/pytorch/hub/assets/24480497/7bc2a230-8158-4111-86cc-2c71810d9b8d)

The first URL (DistilBERT) has now moved to: https://github.com/huggingface/transformers/tree/main/examples/research_projects/distillation

The blog URL has now moved to:
https://medium.com/huggingface/distilbert-8cf3380435b5

**Comment by sghassemlou** [comment]
The links to the tokenizer documentation are also broken.

**Comment by afifaniks** [comment]
@NicolasHug sure, will do that.
