### ISSUE TITLE
wants to contribute and publish an image classification model.

### ISSUE THREAD

**Issue by tahmeedtoqi** [pytorch/hub#348]
Hi, thanks for providing so many amazing AI model for us AI researchers!
Currently, I want to provide our model (https://github.com/tahmeedtoqi/hub) to PyTorch Hub. And I have added the hubconf.py to my repository and filled the project information in hub/docs/template.md, But there seems to be no news. Did I miss anything? Appreciate very much if you can answer it!

Regards
Tahmeed Al Toqi

**Comment by NicolasHug** [comment]
Hi @tahmeedtoqi 

Tank you for the PR but that model has already been deemed out of scope for the pytorch hub website here: https://github.com/pytorch/hub/pull/345#issuecomment-2032159300

**Comment by tahmeedtoqi** [comment]
i have made some updates so that now it can be called as toy model .(347)

I therefore, request to recheck my model evaluation and rethink about it
your decision

regards
Tahmeed Al Toqi
