### ISSUE TITLE
cannot load the pre-trained model

### ISSUE THREAD

**Issue by Loverush** [pytorch/hub#35]
- windows

- pytorch 1.1

- torchvision 0.3

- cuda 9.0

when I tried '' torch.hub.list('pytorch/vision') '', it happened that:
[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\****/.cache\\torch\\hub\\master.zip'

**Comment by ailzhang** [comment]
This should be fixed in https://github.com/pytorch/pytorch/issues/20757 and will be included in our release (likely in next month). But it's a simple one-liner change you can add in your install. (Or build from master)
