### ISSUE TITLE
overfitting

### ISSUE THREAD

**Issue by fasp-2023** [pytorch/hub#351]
Hi Glen and users of github,

I have a question about overfitting in my model. I have the following graphs:
![image](https://github.com/community/community/assets/129007713/816062f1-ede4-4ec4-a1d6-20744018ef21)

Whit this graphs, how can i say that my model is not in overfitting?

I used k-fold cross validation to test my overfitting with k=10. Results is below:
![image](https://github.com/community/community/assets/129007713/2bde2fe0-783b-4807-905c-5f1a2d66f5bd)

Can you help me with understanding if i have overfitting?

Thank you very much.

Best Regards,

Philip

**Comment by NicolasHug** [comment]
Hi @fasp-2023 , you're in the wrong repo (again :thinking:  https://github.com/pytorch/hub/issues/331#issuecomment-1568060730)
