### ISSUE TITLE
When running waveglow.infer, getting 'RuntimeError: CUDA error: invalid device function' 

### ISSUE THREAD

**Issue by artificalnouveau** [pytorch/hub#62]
When running:
`with torch.no_grad():`
     ` _, mel, _, _ = tacotron2.infer(sequence)`
     `audio = waveglow.infer(mel)`

I get the following error:
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-12-a6ced0eab0c3> in <module>()
      5 with torch.no_grad():
      6     _, mel, _, _ = tacotron2.infer(sequence)
----> 7     audio = waveglow.infer(mel)
      8 audio_numpy = audio[0].data.cpu().numpy()
      9 rate = 22050

2 frames

/root/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/PyTorch/SpeechSynthesis/Tacotron2/waveglow/model.py in forward(self, z, reverse)
     75                     W_inverse = W_inverse.half()
     76                 self.W_inverse = W_inverse
---> 77             z = F.conv1d(z, self.W_inverse, bias=None, stride=1, padding=0)
     78             return z
     79         else:

RuntimeError: CUDA error: invalid device function

**Comment by Kh4L** [comment]
The example itself works well on my machine and the error seem to be specific to the Google Colab env.

Actually, the error indicates that the PyTorch build is not compatible (more precisely the CUDA capability) with the GPU (which is a `Tesla K80` according to `torch.cuda.get_device_name(0)`)

**Comment by soumith** [comment]
i've changed some things that might help. I'll wait for the nightlies tonight to verify. Let's see.

**Comment by soumith** [comment]
i think i might have nailed it down, let's see.
I suspect this was because of a magma upgrade, and the `W.inverse()` call is failing on missing sm37 architecture.

**Comment by soumith** [comment]
I am moving the technical details of issuing a fix to here: https://github.com/pytorch/pytorch/issues/29096

None of my fixes worked as of yet, and I've been trying.

**Comment by soumith** [comment]
Found a fix, the quoted issue has context. Tomorrow's nightlies, and v1.3.1 will have a fix for this.

**Comment by soumith** [comment]
fixed now on Colab!
