### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq.meters'

### ISSUE THREAD

**Issue by nariman9119** [pytorch/hub#86]
Trying to load an ensemble of ru-en translation models, but it gives me such error.
Can not find out why. The version of fairseq is 0.9.0
The code is the same is in the example provided in https://github.com/pytorch/fairseq/tree/master/examples/wmt19#example-usage-torchhub

**Comment by ailzhang** [comment]
Hi @nariman9119 , could you add what pytorch version and the error you get? 
Thanks!

**Comment by amilasilva92** [comment]
Hi, 

I am also currently experiencing the same issue when loading pretrained roberta models to Google colab. The pytorch version is 1.6.0 and the error log is as follows. Thank you for your help in advance.

Using cache found in /root/.cache/torch/hub/pytorch_fairseq_master
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-fe0bf893e2ca> in <module>()
      3 import torch
      4 print(torch.__version__)
----> 5 en_lm = torch.hub.load('pytorch/fairseq', 'transformer_lm.wmt19.en', tokenizer='moses', bpe='fastbpe')
      6 # roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
      7 # roberta.eval()  # disable dropout (or leave in train mode to finetune)

10 frames
/usr/local/lib/python3.6/dist-packages/torch/hub.py in load(github, model, *args, **kwargs)
    347     sys.path.insert(0, repo_dir)
    348 
--> 349     hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
    350 
    351     entry = _load_entry_from_hubconf(hub_module, model)

/usr/local/lib/python3.6/dist-packages/torch/hub.py in import_module(name, path)
     69         spec = importlib.util.spec_from_file_location(name, path)
     70         module = importlib.util.module_from_spec(spec)
---> 71         spec.loader.exec_module(module)
     72         return module
     73     else:

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/root/.cache/torch/hub/pytorch_fairseq_master/hubconf.py in <module>()
      6 import functools
      7 
----> 8 from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
      9 from fairseq.hub_utils import TokenizerHubInterface as tokenizer  # noqa
     10 from fairseq.models import MODEL_REGISTRY

/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/__init__.py in <module>()
     16 
     17 import fairseq.criterions  # noqa
---> 18 import fairseq.models  # noqa
     19 import fairseq.modules  # noqa
     20 import fairseq.optim  # noqa

/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/__init__.py in <module>()
    130     ):
    131         model_name = file[:file.find('.py')] if file.endswith('.py') else file
--> 132         module = importlib.import_module('fairseq.models.' + model_name)
    133 
    134         # extra `model_parser` for sphinx

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/lightconv_lm.py in <module>()
      4 # LICENSE file in the root directory of this source tree.
      5 
----> 6 from fairseq import options
      7 from fairseq.models import (
      8     FairseqLanguageModel,

/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/options.py in <module>()
     10 import torch
     11 
---> 12 from fairseq import scoring, utils
     13 from fairseq.data.indexed_dataset import get_available_dataset_impl
     14 

/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/scoring/__init__.py in <module>()
     12 
     13 build_scoring, register_scoring, SCORING_REGISTRY = registry.setup_registry(
---> 14     "--scoring", default="bleu"
     15 )
     16 

TypeError: 'NoneType' object is not iterable

**Comment by myleott** [comment]
Please try again with `torch.hub.load(..., force_reload=True)`
